name: Deploy to Webapp.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Webapp.io
        uses: webappio/deploy-action@v1
        with:
          webappio_api_key: ${{ secrets.WEBAPP_IO_API_KEY }}
